name: 'Test Application'

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'Dockerfile'
      - '.github/workflows/test-app.yml'
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'Dockerfile'
      - '.github/workflows/test-app.yml'

jobs:
  test:
    name: 'Run Tests'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd app
        pip install -r requirements-dev.txt

    - name: Run tests with coverage
      run: |
        cd app
        coverage run -m pytest test_app.py -v
        coverage report
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./app/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  docker-build:
    name: 'Docker Build Test'
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t flask-app-test .

    - name: Test Docker image
      run: |
        docker run -d -p 5000:5000 --name flask-test flask-app-test
        sleep 10
        curl -f http://localhost:5000/health || exit 1
        docker stop flask-test
        docker rm flask-test